---
apiVersion: v1
kind: Service
metadata:
  name: nayan-app
  labels:
    app: nayan-app
spec:
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: nayan-app
  type: NodePort

...
