apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amazon-clone
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/npkharat/k8s_cicd.git
    targetRevision: main
    path: amazon-clone

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

  #you can create the project manually or use this script to create project - This step should be performed after deploying argoCD.